package enumerations;

public enum Operacoes {
	LOGIN_CANDIDATE,
	LOGOUT_CANDIDATE,
    SIGNUP_CANDIDATE,
    LOOKUP_ACCOUNT_CANDIDATE,
    UPDATE_ACCOUNT_CANDIDATE,
    DELETE_ACCOUNT_CANDIDATE,

}
