package enumerations;

public enum Operacoes {
	
	LOGIN_CANDIDATE,
	LOGOUT_CANDIDATE,
    SIGNUP_CANDIDATE,
    LOOKUP_ACCOUNT_CANDIDATE,
    UPDATE_ACCOUNT_CANDIDATE,
    DELETE_ACCOUNT_CANDIDATE,
    LOGIN_RECRUITER,
    LOGOUT_RECRUITER,
    SIGNUP_RECRUITER,
    LOOKUP_ACCOUNT_RECRUITER,
    UPDATE_ACCOUNT_RECRUITER,
    DELETE_ACCOUNT_RECRUITER,
    NAO_EXISTE,
    
}
